global:
  scrape_interval: 60s # How frequently to scrape targets by default.
  scrape_timeout: 10s # How long until a scrape request times out.
  evaluation_interval: 60s # How frequently to evaluate rules.

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global evaluation_interval.
rule_files:

# A scrape configuration
scrape_configs:
  - job_name: prometheus
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics
    static_configs:
    - targets: ['localhost:9090']
  - job_name: node_exporter
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 10s
    scrape_timeout: 9s
    metrics_path: /metrics
    static_configs:
    - targets: ['cluster1-node1:9200']
    - targets: ['cluster1-node2:9200']
    - targets: ['cluster1-node3:9200']
    - targets: ['cluster2-node1:9200']
    - targets: ['cluster2-node2:9200']
    - targets: ['cluster2-node3:9200']
  - job_name: couchbase-buckets
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics/buckets
    static_configs:
    - targets: ['localhost:5000']
    - targets: ['localhost:5001']
    metric_relabel_configs:
      # if the stat name starts with data_* strip off index_
      - source_labels: [__name__]
        regex: 'data_(.*)'
        replacement: '$1'
        target_label: __name__
      # add data_ to the start of every stat
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'data_$1'
        target_label: __name__
  - job_name: couchbase-indexes
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics/indexes
    static_configs:
    - targets: ['localhost:5000']
    - targets: ['localhost:5001']
    metric_relabel_configs:
      # if the stat name starts with index_* strip off index_
      - source_labels: [__name__]
        regex: 'index_(.*)'
        replacement: '$1'
        target_label: __name__
      # add index_ to the start of every stat
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'index_$1'
        target_label: __name__
  - job_name: couchbase-queries
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics/query
    static_configs:
    - targets: ['localhost:5000']
    - targets: ['localhost:5001']
    metric_relabel_configs:
      # if the stat name starts with query_* strip off index_
      - source_labels: [__name__]
        regex: 'query_(.*)'
        replacement: '$1'
        target_label: __name__
      # add query_ to the start of every stat
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'query_$1'
        target_label: __name__
  - job_name: couchbase-xdcr
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics/xdcr
    static_configs:
    - targets: ['localhost:5000']
    - targets: ['localhost:5001']
    metric_relabel_configs:
      # if the stat name starts with xdcr_* strip off index_
      - source_labels: [__name__]
        regex: 'xdcr_(.*)'
        replacement: '$1'
        target_label: __name__
      # add xdcr_ to the start of every stat
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'xdcr_$1'
        target_label: __name__
  - job_name: couchbase-system
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics/system
    static_configs:
    - targets: ['localhost:5000']
    - targets: ['localhost:5001']
    metric_relabel_configs:
      # if the stat name starts with system_* strip off index_
      - source_labels: [__name__]
        regex: 'system_(.*)'
        replacement: '$1'
        target_label: __name__
      # add system_ to the start of every stat
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'system_$1'
        target_label: __name__
  - job_name: couchbase-eventing
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics/eventing
    static_configs:
    - targets: ['localhost:5000']
    - targets: ['localhost:5001']
    metric_relabel_configs:
      # if the stat name starts with eventing_* strip off index_
      - source_labels: [__name__]
        regex: 'eventing_(.*)'
        replacement: '$1'
        target_label: __name__
      # add eventing_ to the start of every stat
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'eventing_$1'
        target_label: __name__
  - job_name: couchbase-analytics
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics/analytics
    static_configs:
    - targets: ['localhost:5000']
    - targets: ['localhost:5001']
    metric_relabel_configs:
      # if the stat name starts with analytics_* strip off index_
      - source_labels: [__name__]
        regex: 'analytics_(.*)'
        replacement: '$1'
        target_label: __name__
      # add analytics_ to the start of every stat
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'analytics_$1'
        target_label: __name__
  - job_name: couchbase-fts
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics/fts
    static_configs:
    - targets: ['localhost:5000']
    - targets: ['localhost:5001']
    metric_relabel_configs:
      # if the stat name starts with fts_* strip off index_
      - source_labels: [__name__]
        regex: 'fts_(.*)'
        replacement: '$1'
        target_label: __name__
      # add fts_ to the start of every stat
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'fts_$1'
        target_label: __name__
